### ISSUE TITLE
Room 6 Cost Bug

### ISSUE THREAD

**Issue by Barnesey41** [tomii-ssb/kashyyyk-hotel-booking#1]
cost of 1 adult staying in room 6 for 1 day = 1GBP
![room 6 for 1gbp]

(https://user-images.githubusercontent.com/74460619/99276216-55e5f680-2824-11eb-8217-538052b97325.PNG)

**Comment by tomii-ssb** [comment]
fixed, there was a slight mistake in the room calculations
