### ISSUE TITLE
wont let user book room in Check In

### ISSUE THREAD

**Issue by theSellotaped** [tomii-ssb/kashyyyk-hotel-booking#12]
after entering valid DOB, number of guests, etc. reach room booking and rather than letting user book a room and giving them a bookingID, outputs error message and takes them back to the start.

only way i've managed to get a bookingID is by inputting 0 guests staying for 0 days, which is also an issue

**Comment by Barnesey41** [comment]
Fixed. operator sign incorrect way line 219 of check_in file.
