### ISSUE TITLE
Dates which dont exist can be entered for DOB & current date

### ISSUE THREAD

**Issue by Barnesey41** [tomii-ssb/kashyyyk-hotel-booking#13]
for example, you may enter the 31st of February or the 20th month. This apples to DOB in check_in & current date in check_out.

**Comment by theSellotaped** [comment]
the way the date is stored means that i dont think you can put limits on it? as its stored as one whole integer rather than three seperate ints. ill have a look but im guessing that we'd have to change how its stored as a whole,

**Comment by Barnesey41** [comment]
i can fix this on the check_out section as mine is stored as 3 seperate int but for yours i don't think we can

**Comment by theSellotaped** [comment]
i mean we could try just outright replacing how its stored in the check in, like asking for date, month and year seperately, but that might take a while and we aint got much time
