### ISSUE TITLE
table array doesnt remove booked table

### ISSUE THREAD

**Issue by theSellotaped** [tomii-ssb/kashyyyk-hotel-booking#14]
when table is booked, the array doesn't remove the element or replace with it "BOOKED", you can also still book the same table even when its supposed to have been booked.

int booking() {

    if (booked_table.booked) //checks if table is already booked and breaks without booking if so
    {
        printf("Table already booked.");
        return 1;
    } else {
        booked_table.booked = 1; //changes elements name to "BOOKED" so that it cannot be booked again until the program is rebooted

        printf("\nYou have successfully booked the %s table at %s :)\n", booked_table.name, booked_table.time);
    }

    return 0;
}

i'm not sure but i think the issue is somewhere in here

**Comment by Barnesey41** [comment]
i think that rather than using booked tommi has changed it for using 0 as not being booked and 1 as being booked, just the comment alongside this code wasn't updated?

**Comment by tomii-ssb** [comment]
fixed, if the table's booked value is 1 then it will not display and cannot be booked
