### ISSUE TITLE
Room Booking Issue

### ISSUE THREAD

**Issue by Barnesey41** [tomii-ssb/kashyyyk-hotel-booking#4]
Rooms can be booked despite not being shown as available and being currently occupied

![Room booked despite not being shown as available](https://user-images.githubusercontent.com/74460619/99280181-f63e1a00-2828-11eb-903e-1d6bca587b66.PNG)

**Comment by tomii-ssb** [comment]
fixed, simply added if statement to check if booked value in rooms array is set to 1 (booked), and if it is, output error message and restart func
