### ISSUE TITLE
numerical charecters as surname

### ISSUE THREAD

**Issue by Barnesey41** [tomii-ssb/kashyyyk-hotel-booking#9]
users can enter surname as numerical characters

![numerical charectered surname](https://user-images.githubusercontent.com/74460619/99396914-37dacd80-28da-11eb-8ab1-813fbe88b769.PNG)

**Comment by theSellotaped** [comment]
fixed it, added a for loop which checks whether there are any numbers in the name and starts again if there is :)

    printf("Please enter your surname (in lowercase):\n");
    fflush(stdin);
    if (scanf("%s", sur)) {}
    else {
        printf("\nAn error occurred, please try again :/\n");
        get_usr_info(sur, brd, ln, c_num, a_num, wakeup);
    }

    for (int i = 0; sur[i] != '\0'; i++) {
        if (sur[i] == '0' || sur[i] == '1' || sur[i] == '2' || sur[i] == '3' || sur[i] == '5' || sur[i] == '6' || sur[i] == '7' || sur[i] == '8' || sur[i] == '9') {
            printf("\nPlease try again without any numbers :/\n");
            get_usr_info(sur, brd, ln, c_num, a_num, wakeup);
        }
    }
